name: unfollowerscurrent
description: VERDICT - Professional Follower Analyzer.
publish_to: 'none'
version: 26.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  webview_flutter: ^4.7.0
  webview_flutter_wkwebview: ^3.23.6
  shared_preferences: ^2.2.2
  http: ^1.6.0
  url_launcher: ^6.2.4
  google_mobile_ads: ^7.0.0
  gma_mediation_unity: ^1.6.4
  package_info_plus: ^9.0.0
  flutter_local_notifications: ^20.1.0
  timezone: ^0.10.1
  app_tracking_transparency: ^2.0.5
  purchases_flutter: ^9.11.0
  device_info_plus: ^12.3.0

  firebase_core: ^4.4.0
  firebase_analytics: ^12.1.2
  firebase_remote_config: ^6.1.4
  firebase_messaging: ^16.1.1
  cloud_firestore: ^6.1.2
  firebase_auth: ^6.1.4
  firebase_crashlytics: ^5.0.7
  webview_flutter_android: ^4.10.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png
