org.gradle.jvmargs=-Xms512m -Xmx3G -Xss512k -XX:MaxMetaspaceSize=768m -XX:ReservedCodeCacheSize=192m -XX:HeapBaseMinAddress=1G -XX:CICompilerCount=2 -XX:ActiveProcessorCount=4 -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.daemon=false
org.gradle.workers.max=1
org.gradle.vfs.watch=false
kotlin.compiler.execution.strategy=in-process
kotlin.daemon.jvmargs=-Xms128m -Xmx768m -Xss512k
android.useAndroidX=true
android.overridePathCheck=true
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
org.gradle.java.home=C:/Program Files/Microsoft/jdk-17.0.20.101-hotspot
